Repository Lab20-Mosobamboo/Monstera, pull requests merged in 2023-03, with the labels that each got.

#15 Carousel 공동 컴포넌트 구현, Link 컴포넌트 오류 수정
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.stories.js
  src/components/Carousel/carousel.css
  src/components/Link/Link.jsx
  src/components/Link/Link.stories.js
Labels: ✨ Feature, 🐞 BugFix, ⚙ Setting

#16 아코디언 컴포넌트 구현
  .github/ISSUE_TEMPLATE/✅feature.md
  .github/ISSUE_TEMPLATE/🐞bug.md
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.stories.js
  src/components/Accordion/accordion.css
Labels: ✨ Feature

#17 [feat] Add Table compopnent
  .storybook/preview.js
  package-lock.json
  src/components/Link/Link.jsx
  src/components/Link/Link.stories.js
Labels: ✨ Feature

#32 Card Components 완성
  .gitignore
  package-lock.json
  src/App.jsx
  src/assets/images/card_image.png
  src/assets/images/vuesax/linear/vuesax/linear/Vector.svg
  src/components/Card/Card.jsx
  src/components/Card/Card.stories.js
  src/components/Card/card.css
  src/components/Card/reset.css
Labels: ✨ Feature

#33 Complete Inspection Guide Container
  src/containers/InspectionGuide/InspectionGuide.jsx
  src/containers/InspectionGuide/InspectionGuide.stories.js
  src/containers/InspectionGuide/inspectionGuide.css
Labels: ✨ Feature

#35 Purchase Guide Container Complete
  src/containers/PurchaseGuide/PurchaseGuide.jsx
  src/containers/PurchaseGuide/PurchaseGuide.stories.js
  src/containers/PurchaseGuide/purchaseGuide.css
Labels: 🎨 Html&css

#42 Product Detail Page Complete
  src/components/Table/Table.jsx
  src/components/Table/Table.stories.js
  src/components/Table/table.css
  src/containers/InspectionGuide/inspectionGuide.css
  src/containers/PriceInfo/PriceInfo.jsx
  src/containers/PriceInfo/PriceInfo.stories.js
  src/containers/PriceInfo/priceInfo.css
  src/containers/ProductGuide/ProductGuide.jsx
  src/containers/ProductGuide/ProductGuide.stories.js
  src/containers/ProductGuide/productGuide.css
  src/containers/ProductInfo/ProductInfo.jsx
  src/containers/ProductInfo/ProductInfo.stories.js
  src/containers/ProductInfo/productInfo.css
  src/containers/PurchaseGuide/purchaseGuide.css
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetail.stories.js
  src/pages/ProductDetail/productDetail.css
Labels: ✨ Feature
